In [890]:
import pandas as pd
import numpy as np

In [891]:
data = pd.read_csv("batting_stacked_hwh_fpos.csv")
data.head()

Unnamed: 0  player_id  year-0  g-0  ab-0  r-0  h-0  double-0  triple-0  \
0           0  ordazlu01    1997   12    22    3    6         1         0   
1           1  schmimi01    1972   13    34    2    7         0         0   
2           2  thomeji01    1991   27    98    7   25         4         2   
3           3   diazma02    2003    4     9    2    1         0         0   
4           4  taubeed01    1991   26    66    5   16         2         1   

   hr-0  ...       1B     2B     3B      C  CF     DH    LF  P     RF     SS  
0     0  ...    0.000  0.351  0.050  0.000   0  0.000  0.00  0  0.000  0.599  
1     1  ...    0.003  0.008  0.972  0.000   0  0.000  0.00  0  0.000  0.018  
2     1  ...    0.000  0.000  0.996  0.000   0  0.004  0.00  0  0.000  0.000  
3     0  ...    0.008  0.000  0.000  0.000   0  0.000  0.94  0  0.053  0.000  
4     0  ...    0.007  0.000  0.000  0.993   0  0.000  0.00  0  0.000  0.000  

[5 rows x 263 columns]

In [892]:
yvals = pd.read_csv("batting_yarr.csv")
yvals.head()
#unfortunately, we have more yvals than data points

player_id    0    1    2    3    4    5    6    7    8    9
0  ordazlu01  0.0  0.0  0.0 -0.1  0.0  0.0  0.0  0.0  0.0  0.0
1  distebe01  0.0  0.0 -0.1  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  schmimi01  6.2  7.9  8.8  7.7  7.4  6.8  7.0  5.0  6.1  6.1
3  thomeji01  5.5  3.3  4.5  4.7  5.6  7.4  4.7  3.2  0.2  4.9
4   diazma02  1.7  0.6 -0.9 -0.8 -0.1  0.0  0.0  0.0  0.0  0.0

In [893]:
yvals = pd.merge(yvals, data[["player_id"]], how="inner", left_on="player_id", right_on="player_id")
yvals.head()
#now, it's fixed

player_id    0    1    2    3    4    5    6    7    8    9
0  ordazlu01  0.0  0.0  0.0 -0.1  0.0  0.0  0.0  0.0  0.0  0.0
1  schmimi01  6.2  7.9  8.8  7.7  7.4  6.8  7.0  5.0  6.1  6.1
2  thomeji01  5.5  3.3  4.5  4.7  5.6  7.4  4.7  3.2  0.2  4.9
3   diazma02  1.7  0.6 -0.9 -0.8 -0.1  0.0  0.0  0.0  0.0  0.0
4  taubeed01 -0.1  1.4  1.5 -1.2 -0.3  0.0  0.0  0.0  0.0  0.0

In [894]:
#just predict year 7 (0) for now
y = yvals["0"].as_matrix()
y

array([ 0. ,  7.9,  3.3, ...,  5.6,  2.5,  0.5])

In [895]:
for col in data.columns:
    print(col)

Unnamed: 0
player_id
year-0
g-0
ab-0
r-0
h-0
double-0
triple-0
hr-0
rbi-0
sb-0
cs-0
bb-0
so-0
ibb-0
hbp-0
sh-0
sf-0
g_idp-0
ob-0
pa-0
tb-0
war-0
ab_per_g-0
r_per_ab-0
batting_avg-0
double_per_ab-0
triple_per_ab-0
hr_per_ab-0
rbi_per_ab-0
sb_per_ob-0
cs_per_ob-0
sb_ratio-0
bb_per_pa-0
so_per_ab-0
slg-0
obp-0
rc-0
rc_per_ab-0
babip-0
iso-0
pa_per_so-0
year-1
g-1
ab-1
r-1
h-1
double-1
triple-1
hr-1
rbi-1
sb-1
cs-1
bb-1
so-1
ibb-1
hbp-1
sh-1
sf-1
g_idp-1
ob-1
pa-1
tb-1
war-1
ab_per_g-1
r_per_ab-1
batting_avg-1
double_per_ab-1
triple_per_ab-1
hr_per_ab-1
rbi_per_ab-1
sb_per_ob-1
cs_per_ob-1
sb_ratio-1
bb_per_pa-1
so_per_ab-1
slg-1
obp-1
rc-1
rc_per_ab-1
babip-1
iso-1
pa_per_so-1
year-2
g-2
ab-2
r-2
h-2
double-2
triple-2
hr-2
rbi-2
sb-2
cs-2
bb-2
so-2
ibb-2
hbp-2
sh-2
sf-2
g_idp-2
ob-2
pa-2
tb-2
war-2
ab_per_g-2
r_per_ab-2
batting_avg-2
double_per_ab-2
triple_per_ab-2
hr_per_ab-2
rbi_per_ab-2
sb_per_ob-2
cs_per_ob-2
sb_ratio-2
bb_per_pa-2
so_per_ab-2
slg-2
obp-2
rc-2
rc_per_ab-2
babip-2
iso-

In [896]:
#remove things we obviously won't care about
for_rem = ["Unnamed: 0", "triple_per_ab-0", "triple-0", "cs-0", "ibb-0", "hbp-0", "sh-0", "sf-0", "g_idp-0", "ab_per_g-0", "r_per_ab-0", "double_per_ab-0", "cs_per_ob-0",
          "triple_per_ab-1", "triple-1", "cs-1", "ibb-1", "hbp-1", "sh-1", "sf-1", "g_idp-1", "ab_per_g-1", "r_per_ab-1", "double_per_ab-1", "cs_per_ob-1",
          "triple_per_ab-2", "triple-2", "cs-2", "ibb-2", "hbp-2", "sh-2", "sf-2", "g_idp-2", "ab_per_g-2", "r_per_ab-2", "double_per_ab-2", "cs_per_ob-2",
          "triple_per_ab-3", "triple-3", "cs-3", "ibb-3", "hbp-3", "sh-3", "sf-3", "g_idp-3", "ab_per_g-3", "r_per_ab-3", "double_per_ab-3", "cs_per_ob-3",
          "triple_per_ab-4", "triple-4", "cs-4", "ibb-4", "hbp-4", "sh-4", "sf-4", "g_idp-4", "ab_per_g-4", "r_per_ab-4", "double_per_ab-4", "cs_per_ob-4",
          "triple_per_ab-5", "triple-5", "cs-5", "ibb-5", "hbp-5", "sh-5", "sf-5", "g_idp-5", "ab_per_g-5", "r_per_ab-5", "double_per_ab-5", "cs_per_ob-5"]

data = data.drop(for_rem, axis = 1)

In [897]:
#things we probably don't care about.......but keep them in a separate category

for_rem2 = ["g-0", "rbi-0", "ob-0", "pa-0", "rbi_per_ab-0",
            "g-1", "rbi-1", "ob-1", "pa-1", "rbi_per_ab-1",
            "g-2", "rbi-2", "ob-2", "pa-2", "rbi_per_ab-2",
            "g-3", "rbi-3", "ob-3", "pa-3", "rbi_per_ab-3",
            "g-4", "rbi-4", "ob-4", "pa-4", "rbi_per_ab-4",
            "g-5", "rbi-5", "ob-5", "pa-5", "rbi_per_ab-5"]

data = data.drop(for_rem2, axis = 1)

In [898]:
#preliminary list of what we DO CARE ABOUT

#care = ["player_id", "year-0", "ab-3", "war-3", "babip-3", "so_per_ab-3",
#          "ab-4", "war-4", "babip-4", "so_per_ab-4",
#          "ab-5", "war-5", "babip-5", "so_per_ab-5",
#          " 6th_year_age", "weight", "height", "bats", "1B", "2B", "3B", "C", "CF", "DH", "LF", "RF", "SS"]

#war = ["war-0", "war-1", "war-2", "war-3", "war-4", "war-5"]

#data = data[care]
data = data.drop("throws", axis = 1)
#data = data.drop(war, axis = 1)

In [899]:
data

player_id  year-0  ab-0  r-0  h-0  double-0  hr-0  sb-0  bb-0  so-0  \
0     ordazlu01    1997    22    3    6         1     0     3     1     2   
1     schmimi01    1972    34    2    7         0     1     0     5    15   
2     thomeji01    1991    98    7   25         4     1     1     5    16   
3      diazma02    2003     9    2    1         0     0     0     1     3   
4     taubeed01    1991    66    5   16         2     0     0     5    16   
5     wilkiri01    1991   203   21   45         9     6     3    19    56   
6     jamesdi01    1983    20    1    2         0     0     1     2     2   
7     harpete01    1980    54    3   10         2     0     2     6     5   
8      dentbu01    1973   117   17   29         2     0     2    10    18   
9     sakatle01    1977   154   13   25         2     2     1     9    22   
10    flahejo01    1992    66    3   13         2     0     0     3     7   
11    molinjo01    1999    19    3    5         1     0     0     2     4   
12    wynnema01    1983   366   66   89        16     7    12    38    52   
13    hatchmi01    1979    93    9   25         4     1     1     7    12   
14    allenga01    1979   241   27   49        10     3     1    20    42   
15    maciajo01    1999     4    2    1         0     1     0     0     1   
16    michaja01    2001     6    0    1         0     0     0     0     2   
17    gallemi01    1985    77   13   16         5     1     1    12    14   
18    yeagest01    1972   106   18   29         0     4     0    16    26   
19    corpoca01    2009     1    1    1         0     0     0     0     0   
20    rodrihe02    1992   146   11   32         7     3     0     8    30   
21    footeba01    1973     6    0    4         0     0     0     0     0   
22    gilesbr02    1995     9    6    5         0     1     0     0     1   
23    nahorbi01    1976     5    0    1         1     0     0     0     0   
24    dernibo01    1980     7    5    4         0     0     3     1     0   
25    mccanbr01    2005   180   20   50         7     5     1    18    26   
26    flannti01    1979    65    2   10         0     0     0     4     5   
27    johnsti01    1973   465   39   99        10     0     6    29    93   
28    seitzke01    1986    96   16   31         4     2     0    19    14   
29    tagucso01    2002    15    4    6         0     0     1     2     1   
...         ...     ...   ...  ...  ...       ...   ...   ...   ...   ...   
1543  avilaal01    2009    61    9   17         4     5     0    10    18   
1544  wilforo01    1977   171   22   42         1     1    10    17    26   
1545  martica01    1983    89    8   23         3     6     0     4    19   
1546  francbe01    2007    62   10   17         5     3     0     3    19   
1547  gilbrro01    1972    38    2    9         1     0     1     2    10   
1548  lavalmi01    1984     7    0    0         0     0     0     2     2   
1549  juraked01    1982    21    3    7         0     0     0     2     4   
1550   pauljo01    1999    18    2    4         1     0     0     0     4   
1551  esaskni01    1983   302   41   80        10    12     6    27    99   
1552  caseyse01    1997    10    1    2         0     0     0     1     2   
1553  suzukic01    2001   692  127  242        34     8    56    30    53   
1554  wohlfji01    1972    25    3    6         1     0     0     2     6   
1555  betanyu01    2005   211   24   54        11     1     1    11    24   
1556  hardyjj01    2005   372   46   92        22     9     0    44    48   
1557  crosbbo01    2003    12    1    0         0     0     0     1     5   
1558  gaettga01    1981    26    4    5         0     2     0     0     6   
1559  disarga01    1989     0    0    0         0     0     0     0     0   
1560  eusebto01    1991    19    4    2         1     0     0     6     8   
1561  coninje01    1990    20    3    5         2     0     0     2     5   
1562  schofdi02    1983    54    4   11         2     3     0     6     8   
15

In [900]:
data["decade"] = np.floor((data["year-0"] - 1970)/10)

data = data.drop("year-0", axis=1)
data.head()


player_id  ab-0  r-0  h-0  double-0  hr-0  sb-0  bb-0  so-0  tb-0   ...    \
0  ordazlu01    22    3    6         1     0     3     1     2     7   ...     
1  schmimi01    34    2    7         0     1     0     5    15    10   ...     
2  thomeji01    98    7   25         4     1     1     5    16    36   ...     
3   diazma02     9    2    1         0     0     0     1     3     1   ...     
4  taubeed01    66    5   16         2     0     0     5    16    20   ...     

      2B     3B      C  CF     DH    LF  P     RF     SS  decade  
0  0.351  0.050  0.000   0  0.000  0.00  0  0.000  0.599       2  
1  0.008  0.972  0.000   0  0.000  0.00  0  0.000  0.018       0  
2  0.000  0.996  0.000   0  0.004  0.00  0  0.000  0.000       2  
3  0.000  0.000  0.000   0  0.000  0.94  0  0.053  0.000       3  
4  0.000  0.000  0.993   0  0.000  0.00  0  0.000  0.000       2  

[5 rows x 159 columns]

In [901]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
lb.fit(data["decade"])
binarized = lb.transform(data["decade"])
bins = pd.DataFrame(binarized)
bins.head()

0  1  2  3
0  0  0  1  0
1  1  0  0  0
2  0  0  1  0
3  0  0  0  1
4  0  0  1  0

In [902]:
bins = bins.rename(columns = {0 : "1970s", 1 : "1980s", 2 : "1990s", 3 : "2000s"})
bins.head()

1970s  1980s  1990s  2000s
0      0      0      1      0
1      1      0      0      0
2      0      0      1      0
3      0      0      0      1
4      0      0      1      0

In [903]:
data = pd.merge(data, bins, how="left", left_index=True, right_index=True)
data = data.drop("decade", axis = 1)
data.head()

player_id  ab-0  r-0  h-0  double-0  hr-0  sb-0  bb-0  so-0  tb-0  ...    \
0  ordazlu01    22    3    6         1     0     3     1     2     7  ...     
1  schmimi01    34    2    7         0     1     0     5    15    10  ...     
2  thomeji01    98    7   25         4     1     1     5    16    36  ...     
3   diazma02     9    2    1         0     0     0     1     3     1  ...     
4  taubeed01    66    5   16         2     0     0     5    16    20  ...     

   CF     DH    LF  P     RF     SS  1970s  1980s  1990s  2000s  
0   0  0.000  0.00  0  0.000  0.599      0      0      1      0  
1   0  0.000  0.00  0  0.000  0.018      1      0      0      0  
2   0  0.004  0.00  0  0.000  0.000      0      0      1      0  
3   0  0.000  0.94  0  0.053  0.000      0      0      0      1  
4   0  0.000  0.00  0  0.000  0.000      0      0      1      0  

[5 rows x 162 columns]

In [904]:
data = data.drop("player_id", axis = 1)
data.head()

ab-0  r-0  h-0  double-0  hr-0  sb-0  bb-0  so-0  tb-0  war-0  ...    CF  \
0    22    3    6         1     0     3     1     2     7    0.1  ...     0   
1    34    2    7         0     1     0     5    15    10    0.1  ...     0   
2    98    7   25         4     1     1     5    16    36   -0.1  ...     0   
3     9    2    1         0     0     0     1     3     1   -0.1  ...     0   
4    66    5   16         2     0     0     5    16    20    0.0  ...     0   

      DH    LF  P     RF     SS  1970s  1980s  1990s  2000s  
0  0.000  0.00  0  0.000  0.599      0      0      1      0  
1  0.000  0.00  0  0.000  0.018      1      0      0      0  
2  0.004  0.00  0  0.000  0.000      0      0      1      0  
3  0.000  0.94  0  0.053  0.000      0      0      0      1  
4  0.000  0.00  0  0.000  0.000      0      0      1      0  

[5 rows x 161 columns]

In [905]:
#still need to binarize handedness

lbh = LabelBinarizer()
lbh.fit(data["bats"])
binh = lbh.transform(data["bats"])
binh = pd.DataFrame(binh)
binh = binh.rename(columns = {0 : "S", 1 : "L", 2 : "R"})
binh.head()

S  L  R
0  0  0  1
1  0  0  1
2  0  1  0
3  0  0  1
4  0  1  0

In [906]:
data = pd.merge(data, binh, how="left", left_index=True, right_index=True)
data = data.drop("bats", axis = 1)
data.head()

ab-0  r-0  h-0  double-0  hr-0  sb-0  bb-0  so-0  tb-0  war-0 ...  P  \
0    22    3    6         1     0     3     1     2     7    0.1 ...  0   
1    34    2    7         0     1     0     5    15    10    0.1 ...  0   
2    98    7   25         4     1     1     5    16    36   -0.1 ...  0   
3     9    2    1         0     0     0     1     3     1   -0.1 ...  0   
4    66    5   16         2     0     0     5    16    20    0.0 ...  0   

      RF     SS  1970s  1980s  1990s  2000s  S  L  R  
0  0.000  0.599      0      0      1      0  0  0  1  
1  0.000  0.018      1      0      0      0  0  0  1  
2  0.000  0.000      0      0      1      0  0  1  0  
3  0.053  0.000      0      0      0      1  0  0  1  
4  0.000  0.000      0      0      1      0  0  1  0  

[5 rows x 163 columns]

In [907]:
#Convert to matrix
X = data.as_matrix()
X[0:10]

array([[  22.,    3.,    6., ...,    0.,    0.,    1.],
       [  34.,    2.,    7., ...,    0.,    0.,    1.],
       [  98.,    7.,   25., ...,    0.,    1.,    0.],
       ..., 
       [  54.,    3.,   10., ...,    0.,    0.,    1.],
       [ 117.,   17.,   29., ...,    0.,    0.,    1.],
       [ 154.,   13.,   25., ...,    0.,    0.,    1.]])

In [908]:
from sklearn.preprocessing import MinMaxScaler

Scaler = MinMaxScaler()
Scaler.fit(X)
X = Scaler.transform(X)
X[0:2]

array([[ 0.03179191,  0.02362205,  0.02479339,  0.0212766 ,  0.        ,
         0.02727273,  0.01030928,  0.01081081,  0.01944444,  0.02564103,
         0.27272727,  0.        ,  0.14285714,  1.        ,  0.04347826,
         0.09090909,  0.18181818,  0.30434783,  0.01482844,  0.07057341,
         0.3       ,  0.04545455,  0.21      ,  0.69230769,  0.21825963,
         0.07377049,  0.14761905,  0.10204082,  0.        ,  0.01869159,
         0.08695652,  0.08823529,  0.09863014,  0.01123596,  0.27015251,
         0.        ,  0.02272728,  1.        ,  0.14117648,  0.11764706,
         0.21176471,  0.34747475,  0.06696906,  0.09828571,  0.22962963,
         0.04357299,  0.15705128,  0.69230769,  0.01293103,  0.0212766 ,
         0.0044843 ,  0.        ,  0.        ,  0.00917431,  0.00819672,
         0.00896861,  0.00253807,  0.01020408,  0.11111111,  0.        ,
         0.05882353,  1.        ,  0.18181818,  0.22222222,  0.07407407,
         0.2       ,  0.00116873,  0.01333333,  0.1

In [909]:
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import GridSearchCV

alphas = [0.01, 0.1, 1, 10, 100]
nodes = [(6), (8), (10), (12), (14), (8, 3), (10, 3), (12, 4), (14, 5)]
params = {"alpha" : alphas, "hidden_layer_sizes" : nodes}

In [910]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, y, test_size = 0.25, random_state=12345)

In [911]:
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [998]:
from sklearn.linear_model import Ridge

#linear feature selector
from sklearn.feature_selection import RFE

Rge = Ridge(alpha = 2)

feat = 12

myRFE = RFE(Rge, n_features_to_select=feat, step = 1)

In [1000]:
myRFE.fit(Xtrain, Ytrain)

RFE(estimator=Ridge(alpha=2, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
  n_features_to_select=12, step=1, verbose=0)

In [1001]:
myRFE.ranking_

array([  9,  17,  74,  38,   8,  10,  75,  22,  85,  81,  51, 140,  77,
       109,  66,  76,  91,  19, 147,  24,  23,  18,  31,  80,  32,  33,
        99, 103,  57, 106,  42,  21, 102,  54, 122,  58,   1,  89, 114,
       128, 100,  59,  53, 132,   6,  67,  92,  90,  71,  14, 121,  70,
        15,  88, 112,  40, 131,  64, 143,  83, 113, 133, 134,  46,  97,
       119, 137,  98,  16,  45,  65,  62,  68,   2,  25,  69,   1,  55,
        26,  93,  73,   1,  44,  79, 144, 142, 110,  43, 101, 111, 138,
       129,  84, 149, 146, 105,  52,  11,  12,  34,   1,  56,  48,   1,
        72,   1,  60,   4,  29, 120,  47, 125, 145, 130,  13,  61,  30,
        39,  87,  27, 107,   1,  36,   1,  20,  96,  49, 127, 150,   1,
       115,  50,  63,  35,   1, 126,  86, 135,  37, 141, 136,   1,   7,
         1,   3,   5,  82, 124,  94,  95, 151,  78,  41, 152, 108, 123,
       116, 117, 118,  28, 104, 148, 139])

In [1002]:
colindex = np.argsort(myRFE.ranking_)[0:feat]
colindex

array([ 81,  76, 100, 103, 105, 121, 129, 123, 141, 143, 134,  36])

In [1003]:
best = list(data.columns[colindex])
best

['war-3',
 'hr-3',
 'hr-4',
 'so-4',
 'war-4',
 'r-5',
 'war-5',
 'double-5',
 'iso-5',
 ' 6th_year_age',
 'bb_per_pa-5',
 'sb_per_ob-1']

In [1004]:
from sklearn.metrics import r2_score

In [1005]:
Rdg2 = Ridge()
rdge_alp = {'alpha' : [0.01, 0.1, 1, 10, 100]}
GSrid = GridSearchCV(Rdg2, rdge_alp, return_train_score = True, scoring = 'r2')

In [1006]:
Xtrain_new = Xtrain[:, colindex]
Xtest_new = Xtest[:, colindex]
Xtest_new

array([[ 0.00990099,  0.34042553,  0.16326531, ...,  0.35714286,
         0.26229508,  0.        ],
       [ 0.02970297,  0.        ,  0.06122449, ...,  0.42857143,
         0.21234568,  0.        ],
       [ 0.0990099 ,  0.25531915,  0.20408163, ...,  0.35714286,
         0.16246498,  0.        ],
       ..., 
       [ 0.04950495,  0.0212766 ,  0.06122449, ...,  0.5       ,
         0.2087912 ,  0.05263158],
       [ 0.00990099,  0.        ,  0.28571429, ...,  0.42857143,
         0.22790698,  0.02840909],
       [ 0.02970297,  0.0212766 ,  0.02040816, ...,  0.35714286,
         0.125     ,  0.03164847]])

In [1007]:
GSrid.fit(Xtrain_new, Ytrain)

GridSearchCV(cv=None, error_score='raise',
       estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'alpha': [0.01, 0.1, 1, 10, 100]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='r2', verbose=0)

In [1008]:
GSrid.best_score_

0.40802125120529442

In [1009]:
GSrid.best_params_

{'alpha': 1}

In [1010]:
preds = GSrid.predict(Xtest_new)

r2_score(Ytest, preds)

0.47277310844019826

In [1011]:
alphas = [0.1, 1, 10, 100]
nodes = [(4), (6), (7), (8), (10), (8, 3), (10, 3), (12, 4), (14, 5)]
params = {"alpha" : alphas, "hidden_layer_sizes" : nodes}


MLP = MLPRegressor(activation = 'relu', solver = 'lbfgs', random_state = 54321)

GS = GridSearchCV(MLP, params, return_train_score = True, scoring = 'r2')

In [1012]:
GS.fit(Xtrain_new, Ytrain)

GridSearchCV(cv=None, error_score='raise',
       estimator=MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=54321,
       shuffle=True, solver='lbfgs', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'alpha': [0.1, 1, 10, 100], 'hidden_layer_sizes': [4, 6, 7, 8, 10, (8, 3), (10, 3), (12, 4), (14, 5)]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='r2', verbose=0)

In [1013]:
GS.best_score_

0.40844721073773388

In [1014]:
GS.best_params_

{'alpha': 10, 'hidden_layer_sizes': 4}

In [1015]:
preds = GS.predict(Xtest_new)

r2_score(Ytest, preds)

0.4789674629386883

In [1016]:
from sklearn.tree import DecisionTreeRegressor

DTR = DecisionTreeRegressor()

mx_depth = [2, 3, 4, 5, 6, 7]
mn_lf_splt = [1, 2, 3, 4]
param_tree = {"max_depth" : mx_depth, "min_samples_leaf" : mn_lf_splt}
GStree = GridSearchCV(DTR, param_tree, return_train_score=True, scoring='r2')

In [1017]:
GStree.fit(Xtrain_new, Ytrain)

GridSearchCV(cv=None, error_score='raise',
       estimator=DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best'),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'min_samples_leaf': [1, 2, 3, 4], 'max_depth': [2, 3, 4, 5, 6, 7]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='r2', verbose=0)

In [1018]:
GStree.best_score_

0.30901666606255113

In [1019]:
GStree.best_params_

{'max_depth': 2, 'min_samples_leaf': 3}

In [1020]:
tree_preds = GStree.predict(Xtest_new)

r2_score(Ytest, tree_preds)

0.39475854986581316

In [1021]:
from sklearn.svm import SVR

svr = SVR(kernel = 'rbf')
Cval = [100, 500, 1000, 2000]
eps = [0.000001, 0.00001, 0.0001, 0.001]
gamma = [0.1, 0.01, 0.001, 0.0001]
svm_dict = {"C" : Cval, "epsilon" : eps, "gamma" : gamma}
GSsvm = GridSearchCV(svr, svm_dict, return_train_score = True, scoring = 'r2')

In [1022]:
GSsvm.fit(Xtrain_new, Ytrain)

GridSearchCV(cv=None, error_score='raise',
       estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [100, 500, 1000, 2000], 'epsilon': [1e-06, 1e-05, 0.0001, 0.001], 'gamma': [0.1, 0.01, 0.001, 0.0001]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='r2', verbose=0)

In [1023]:
GSsvm.best_params_

{'C': 1000, 'epsilon': 1e-05, 'gamma': 0.001}

In [1024]:
GSsvm.best_score_

0.39565350187298148

In [1025]:
preds_svm = GSsvm.predict(Xtest_new)
r2_score(Ytest, preds_svm)

0.47185586527278744