In [480]:
import pandas as pd
import numpy as np

In [481]:
data = pd.read_csv("pitching_stacked_hwh.csv")
agg = pd.read_csv("pitching_agg.csv")
data = pd.merge(data, agg, how="inner", left_on="player_id", right_on="player_id")
data.head()

Unnamed: 0  Unnamed: 0.1  player_id  year-0  g-0  w-0  l-0  gs-0  cg-0  \
0           0             0  hamiljo02    1994   16    9    6    16     1   
1           1             1  nelsojo01    2001    2    0    0     0     0   
2           2             2  lopezro01    2000    6    0    3     6     0   
3           3             3  spradje01    1993   37    2    1     0     0   
4           4             4  powelde01    1985   16    1    1     2     0   

   sho-0    ...      cg_per_g  sho_per_g  sv_per_g  ipouts_per_g  bb_per_bfp  \
0      1    ...      0.041667   0.023810  0.000000     18.440476    0.086152   
1      0    ...      0.000000   0.000000  0.187500      3.083333    0.128319   
2      0    ...      0.036496   0.014599  0.000000     16.386861    0.072891   
3      0    ...      0.000000   0.000000  0.021164      3.502645    0.064732   
4      0    ...      0.000000   0.000000  0.024000      5.640000    0.099812   

   hbp_per_bfp  hr_per_tbf  so_per_tbf  wp_per_bfp  so_per_bb  
0     0.011051    0.023233    0.173620    0.008345   1.819372  
1     0.017699    0.032086    0.262032    0.004425   1.689655  
2     0.007444    0.034436    0.168769    0.004032   2.106383  
3     0.003348    0.028743    0.204790    0.016741   2.948276  
4     0.007533    0.024262    0.139241    0.012241   1.245283  

[5 rows x 289 columns]

In [482]:
for_drop = ["Unnamed: 0", "Unnamed: 0.1"]
data = data.drop(for_drop, axis = 1)

In [483]:
yvals = pd.read_csv("pitching_yarr.csv")
yvals.head()

player_id    0    1    2    3    4    5    6  7  8
0  hamiljo02  1.2 -0.5 -0.3 -0.3  0.0  0.0  0.0  0  0
1  nelsojo01  0.0  1.6  0.0 -0.3  0.0  0.0  0.0  0  0
2  lopezro01 -0.1  1.0  0.0 -0.7 -0.7  0.1 -0.2  0  0
3  spradje01  0.3 -0.7  0.0  0.0  0.0  0.0  0.0  0  0
4  powelde01  0.0  0.2  0.6  0.0  0.0  0.0  0.0  0  0

In [484]:
yvals = pd.merge(yvals, data[["player_id"]], how = "inner", left_on="player_id", right_on = "player_id")
yvals.head()

year = data["year-0"]
year.head()
year = year.as_matrix()

pids = data["player_id"]
pids = pids.as_matrix()
pids

array(['hamiljo02', 'nelsojo01', 'lopezro01', ..., 'radkebr01',
       'norribu01', 'whitema02'], dtype=object)

In [485]:
y = yvals["3"].as_matrix()
y[0:5]

array([-0.3, -0.3, -0.7,  0. ,  0. ])

In [486]:
data["HW_ratio"] = data["height"] / data["weight"]

data = data.drop("bats", axis = 1)

In [487]:
data["decade"] = np.floor((data["year-0"] - 1970)/10)

data = data.drop("year-0", axis=1)
data.head()

player_id  g-0  w-0  l-0  gs-0  cg-0  sho-0  sv-0  ipouts-0  h-0   ...    \
0  hamiljo02   16    9    6    16     1      1     0       326   98   ...     
1  nelsojo01    2    0    0     0     0      0     0         6    7   ...     
2  lopezro01    6    0    3     6     0      0     0        74   40   ...     
3  spradje01   37    2    1     0     0      0     2       147   44   ...     
4  powelde01   16    1    1     2     0      0     1        88   30   ...     

   sv_per_g  ipouts_per_g  bb_per_bfp  hbp_per_bfp  hr_per_tbf  so_per_tbf  \
0  0.000000     18.440476    0.086152     0.011051    0.023233    0.173620   
1  0.187500      3.083333    0.128319     0.017699    0.032086    0.262032   
2  0.000000     16.386861    0.072891     0.007444    0.034436    0.168769   
3  0.021164      3.502645    0.064732     0.003348    0.028743    0.204790   
4  0.024000      5.640000    0.099812     0.007533    0.024262    0.139241   

   wp_per_bfp  so_per_bb  HW_ratio  decade  
0    0.008345   1.819372  0.345455       2  
1    0.004425   1.689655  0.400000       3  
2    0.004032   2.106383  0.394595       3  
3    0.016741   2.948276  0.343478       2  
4    0.012241   1.245283  0.428571       1  

[5 rows x 287 columns]

In [488]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
lb.fit(data["decade"])
binarized = lb.transform(data["decade"])
bins = pd.DataFrame(binarized)
bins.head()

0  1  2  3
0  0  0  1  0
1  0  0  0  1
2  0  0  0  1
3  0  0  1  0
4  0  1  0  0

In [489]:
bins = bins.rename(columns = {0 : "1970s", 1 : "1980s", 2 : "1990s", 3 : "2000s"})
bins.head()

1970s  1980s  1990s  2000s
0      0      0      1      0
1      0      0      0      1
2      0      0      0      1
3      0      0      1      0
4      0      1      0      0

In [490]:
data = pd.merge(data, bins, how="left", left_index=True, right_index=True)
data = data.drop("decade", axis = 1)
data.head()

player_id  g-0  w-0  l-0  gs-0  cg-0  sho-0  sv-0  ipouts-0  h-0  ...    \
0  hamiljo02   16    9    6    16     1      1     0       326   98  ...     
1  nelsojo01    2    0    0     0     0      0     0         6    7  ...     
2  lopezro01    6    0    3     6     0      0     0        74   40  ...     
3  spradje01   37    2    1     0     0      0     2       147   44  ...     
4  powelde01   16    1    1     2     0      0     1        88   30  ...     

   hbp_per_bfp  hr_per_tbf  so_per_tbf  wp_per_bfp  so_per_bb  HW_ratio  \
0     0.011051    0.023233    0.173620    0.008345   1.819372  0.345455   
1     0.017699    0.032086    0.262032    0.004425   1.689655  0.400000   
2     0.007444    0.034436    0.168769    0.004032   2.106383  0.394595   
3     0.003348    0.028743    0.204790    0.016741   2.948276  0.343478   
4     0.007533    0.024262    0.139241    0.012241   1.245283  0.428571   

   1970s  1980s  1990s  2000s  
0      0      0      1      0  
1      0      0      0      1  
2      0      0      0      1  
3      0      0      1      0  
4      0      1      0      0  

[5 rows x 290 columns]

In [491]:
lbh = LabelBinarizer()
lbh.fit(data["throws"])
binh = lbh.transform(data["throws"])
binh = pd.DataFrame(binh)
binh = binh.rename(columns = {0 : "R"})
binh.head()

R
0  1
1  1
2  1
3  1
4  0

In [492]:
data = pd.merge(data, binh, how="left", left_index=True, right_index=True)
data = data.drop("throws", axis = 1)
data.head()

player_id  g-0  w-0  l-0  gs-0  cg-0  sho-0  sv-0  ipouts-0  h-0 ...  \
0  hamiljo02   16    9    6    16     1      1     0       326   98 ...   
1  nelsojo01    2    0    0     0     0      0     0         6    7 ...   
2  lopezro01    6    0    3     6     0      0     0        74   40 ...   
3  spradje01   37    2    1     0     0      0     2       147   44 ...   
4  powelde01   16    1    1     2     0      0     1        88   30 ...   

   hr_per_tbf  so_per_tbf  wp_per_bfp  so_per_bb  HW_ratio  1970s  1980s  \
0    0.023233    0.173620    0.008345   1.819372  0.345455      0      0   
1    0.032086    0.262032    0.004425   1.689655  0.400000      0      0   
2    0.034436    0.168769    0.004032   2.106383  0.394595      0      0   
3    0.028743    0.204790    0.016741   2.948276  0.343478      0      0   
4    0.024262    0.139241    0.012241   1.245283  0.428571      0      1   

   1990s  2000s  R  
0      1      0  1  
1      0      1  1  
2      0      1  1  
3      1      0  1  
4      0      0  0  

[5 rows x 290 columns]

In [493]:
data = data.drop("player_id", axis = 1)
data.head()

g-0  w-0  l-0  gs-0  cg-0  sho-0  sv-0  ipouts-0  h-0  er-0 ...  \
0   16    9    6    16     1      1     0       326   98    36 ...   
1    2    0    0     0     0      0     0         6    7     8 ...   
2    6    0    3     6     0      0     0        74   40    24 ...   
3   37    2    1     0     0      0     2       147   44    19 ...   
4   16    1    1     2     0      0     1        88   30    17 ...   

   hr_per_tbf  so_per_tbf  wp_per_bfp  so_per_bb  HW_ratio  1970s  1980s  \
0    0.023233    0.173620    0.008345   1.819372  0.345455      0      0   
1    0.032086    0.262032    0.004425   1.689655  0.400000      0      0   
2    0.034436    0.168769    0.004032   2.106383  0.394595      0      0   
3    0.028743    0.204790    0.016741   2.948276  0.343478      0      0   
4    0.024262    0.139241    0.012241   1.245283  0.428571      0      1   

   1990s  2000s  R  
0      1      0  1  
1      0      1  1  
2      0      1  1  
3      1      0  1  
4      0      0  0  

[5 rows x 289 columns]

In [494]:
#Convert to matrix
X = data.as_matrix()
X[0:10]

array([[ 16.,   9.,   6., ...,   1.,   0.,   1.],
       [  2.,   0.,   0., ...,   0.,   1.,   1.],
       [  6.,   0.,   3., ...,   0.,   1.,   1.],
       ..., 
       [ 24.,   8.,   9., ...,   0.,   0.,   1.],
       [  3.,   0.,   0., ...,   0.,   0.,   0.],
       [ 21.,   3.,   1., ...,   1.,   0.,   1.]])

In [495]:
from sklearn.preprocessing import MinMaxScaler

Scaler = MinMaxScaler()
Scaler.fit(X)
X = Scaler.transform(X)
X[0:2]

array([[ 0.18987342,  0.52941176,  0.31578947,  0.45714286,  0.0625    ,
         0.25      ,  0.        ,  0.45786517,  0.44144144,  0.31034483,
         0.21875   ,  0.2027972 ,  0.22101449,  0.2       ,  0.27272727,
         0.35294118,  0.46122027,  0.        ,  0.33057851,  0.46127946,
         0.67241379,  0.05521472,  0.23786408,  0.84409257,  1.        ,
         0.5625    ,  0.375     ,  0.6       ,  0.        ,  0.09375   ,
         0.125     ,  0.        ,  0.815     ,  0.12975392,  0.09395974,
         0.02548543,  0.20500373,  0.08053692,  0.23371648,  0.61538462,
         0.36470588,  0.25      ,  0.40909091,  0.75      ,  0.11764706,
         0.25      ,  0.        ,  0.7280285 ,  0.65397924,  0.51851852,
         0.425     ,  0.4       ,  0.45895522,  0.3125    ,  0.0952381 ,
         0.6875    ,  0.7118928 ,  0.01470588,  0.59333333,  0.71506849,
         0.37398374,  0.045677  ,  0.28965517,  0.82418712,  0.96774194,
         0.19354839,  0.29032258,  0.4       ,  0.0

In [496]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, Ytrain, Ytest = train_test_split(X, y, test_size = 0.2, random_state=12345)


In [497]:
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import GridSearchCV

alphas = [0.01, 0.1, 1, 10, 100]
nodes = [(6), (8), (10), (12), (14), (8, 3), (10, 3), (12, 4), (14, 5)]
params = {"alpha" : alphas, "hidden_layer_sizes" : nodes}

In [528]:
from sklearn.linear_model import Ridge

#linear feature selector
from sklearn.feature_selection import RFE

Rge = Ridge(alpha = 2)

feat = 7

myRFE = RFE(Rge, n_features_to_select=feat, step = 1)

In [529]:
myRFE.fit(Xtrain, Ytrain)

RFE(estimator=Ridge(alpha=2, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
  n_features_to_select=7, step=1, verbose=0)

In [530]:
colindex = np.argsort(myRFE.ranking_)[0:feat]
colindex

array([ 94,  11,  19, 265, 264, 172,  60])

In [531]:
best = list(data.columns[colindex])
best

['wp-2', 'bb-0', 'tbf-0', 'era', 'war', 'so-4', 'war-1']

In [532]:
from sklearn.metrics import r2_score
Rdg2 = Ridge()
rdge_alp = {'alpha' : [0.01, 0.1, 1, 10, 100]}
GSrid = GridSearchCV(Rdg2, rdge_alp, return_train_score = True, scoring = 'r2')

In [533]:
Xtrain_new = Xtrain[:, colindex]
Xtest_new = Xtest[:, colindex]
Xtest_new

array([[ 0.15384615,  0.11888112,  0.18294052, ...,  0.06805556,
         0.11683849,  0.02439024],
       [ 0.11538462,  0.        ,  0.01234568, ...,  0.075     ,
         0.        ,  0.        ],
       [ 0.03846154,  0.        ,  0.00224467, ...,  0.08541667,
         0.42955326,  0.00813008],
       ..., 
       [ 0.03846154,  0.04195804,  0.04489338, ...,  0.10416667,
         0.29896907,  0.00813008],
       [ 0.19230769,  0.06293706,  0.06285073, ...,  0.19027778,
         0.2233677 ,  0.07317073],
       [ 0.11538462,  0.16083916,  0.23007856, ...,  0.12916667,
         0.51546392,  0.08130081]])

In [534]:
GSrid.fit(Xtrain_new, Ytrain)

GridSearchCV(cv=None, error_score='raise',
       estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'alpha': [0.01, 0.1, 1, 10, 100]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='r2', verbose=0)

In [535]:
GSrid.best_score_

0.46635138421592542

In [536]:
GSrid.best_params_

{'alpha': 0.1}

In [537]:
preds = GSrid.predict(Xtest_new)

r2_score(Ytest, preds)

0.40550277541631319

In [254]:
alphas = [0.1, 1, 10, 100]
nodes = [(4), (6), (7), (8), (10), (8, 3), (10, 3), (12, 4), (14, 5)]
params = {"alpha" : alphas, "hidden_layer_sizes" : nodes}


MLP = MLPRegressor(activation = 'relu', solver = 'lbfgs', random_state = 54321)

GS = GridSearchCV(MLP, params, return_train_score = True, scoring = 'r2')

In [255]:
GS.fit(Xtrain_new, Ytrain)

GridSearchCV(cv=None, error_score='raise',
       estimator=MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=54321,
       shuffle=True, solver='lbfgs', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'alpha': [0.1, 1, 10, 100], 'hidden_layer_sizes': [4, 6, 7, 8, 10, (8, 3), (10, 3), (12, 4), (14, 5)]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='r2', verbose=0)

In [114]:
GS.best_score_

0.45650324044357105

In [266]:
GS.best_params_

{'alpha': 10, 'hidden_layer_sizes': (10, 3)}

In [267]:
preds = GS.predict(Xtest_new)

r2_score(Ytest, preds)

preds = pd.DataFrame(preds)
preds.to_csv("pitching_year4.csv")

In [278]:
from sklearn.ensemble import RandomForestRegressor

DTR = RandomForestRegressor(n_estimators = 100)

mx_depth = [2, 3, 4, 5, 6, 7]
mn_lf_splt = [1, 2, 3, 4]
param_tree = {"max_depth" : mx_depth, "min_samples_leaf" : mn_lf_splt}
GStree = GridSearchCV(DTR, param_tree, return_train_score=True, scoring='r2')

In [279]:
GStree.fit(Xtrain_new, Ytrain)

GridSearchCV(cv=None, error_score='raise',
       estimator=RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'min_samples_leaf': [1, 2, 3, 4], 'max_depth': [2, 3, 4, 5, 6, 7]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='r2', verbose=0)

In [280]:
GStree.best_score_

0.39870745254250139

In [281]:
GStree.best_params_

{'max_depth': 6, 'min_samples_leaf': 2}

In [282]:
tree_preds = GStree.predict(Xtest_new)

r2_score(Ytest, tree_preds)

0.58047420931454885

In [167]:
from sklearn.svm import SVR

svr = SVR(kernel = 'rbf')
Cval = [ 200, 500, 1000]
eps = [ 0.01, 0.1, 1, 3]
gamma = [0.1, 0.01, 0.001]
svm_dict = {"C" : Cval, "epsilon" : eps, "gamma" : gamma}
GSsvm = GridSearchCV(svr, svm_dict, return_train_score = True, scoring = 'r2')

In [168]:
GSsvm.fit(Xtrain_new, Ytrain)

GridSearchCV(cv=None, error_score='raise',
       estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'epsilon': [0.01, 0.1, 1, 3], 'C': [200, 500, 1000], 'gamma': [0.1, 0.01, 0.001]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='r2', verbose=0)

In [169]:
GSsvm.best_params_

{'C': 500, 'epsilon': 1, 'gamma': 0.01}

In [170]:
GSsvm.best_score_

0.40821285293603715

In [171]:
preds_svm = GSsvm.predict(Xtest_new)
r2_score(Ytest, preds_svm)

0.46101213814022024